### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by Predatorie** [leocavalcante/observable_state#1]
Hi,

Trying to add the dependency fails to resolve with the following output:

`[jasa_ostate] flutter packages get
Running "flutter packages get" in jasa_ostate...                
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because jasa_ostate requires SDK version >=2.1.0-dev.68.0 <3.0.0, version solving failed.

pub get failed (1)
exit code 1`

Here are my project dependencies:

`version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  cached_network_image: ^0.5.1
  flutter_cache_manager: ^0.2.0+1
  intl: ^0.15.7
  duration: ^2.0.4
  
  cupertino_icons: ^0.1.2
  observable_state: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter`

Any help is much appreciated.

**Comment by leocavalcante** [comment]
This is solved, but I'm not currently rolling out every change to Pub.
However, you can get it working using it as a [Git package](https://www.dartlang.org/tools/pub/dependencies#git-packages):

```yaml
dependencies:
  observable_state:
    git: git://github.com/leocavalcante/observable_state.git
```

Ping me on any other issues!

**Be aware** that API may change ;)
