### ISSUE TITLE
Can provider be nested?

### ISSUE THREAD

**Issue by webyom** [leocavalcante/observable_state#9]
Other than a central state provider, can I nest some local providers maintained by individual sub modules?

**Comment by leocavalcante** [comment]
Hm, no, sorry. Maybe https://pub.dartlang.org/packages/provider fits your needs.

**Comment by webyom** [comment]
I have done a test, and it works. This lib is really lightweight, easy to adopt and powerful enough for my app. Hierarchical providers and state management is helpful. Since it works now, is there any chance to break this in the future?

**Comment by leocavalcante** [comment]
With "break this in the future" you mean: stop being actively maintained?

**Comment by webyom** [comment]
Your answer is provider can't be nested, but my test proves it does supported. So supporting nested provider is not in your design, I'm worrying about this feature may be removed in the future release.

**Comment by leocavalcante** [comment]
Hm, got it. Well, Context nesting will be a long run on Flutter I guess and observable state is going to a stable API, so I guess your LTS covered 😉
